# Generated by Django 2.2.4 on 2022-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GloboId', models.CharField(max_length=100)),
                ('TelegramId', models.PositiveIntegerField()),
                ('Escolaridade', models.CharField(max_length=100)),
                ('ExperiênciaProfissional', models.CharField(max_length=100)),
                ('CidadedeInteresse', models.CharField(max_length=100)),
                ('PretensaoSalarial', models.PositiveIntegerField()),
                ('AreadeInteresse', models.CharField(max_length=100)),
                ('CursosExtracurriculares', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escolaridade', models.CharField(choices=[('EF1I', 'Ensino fundamental 1 incompleto'), ('EF1C', 'Ensino fundamental 1 completo'), ('EF2I', 'Ensino fundamental 2 incompleto'), ('EF2I', 'Ensino fundamental 2 completo'), ('EMI', 'Ensino medio incompleto'), ('EMC', 'Ensino medio completo'), ('ESI', 'Ensino superior incompleto'), ('ESI', 'Ensino superior completo')], default='EF1I', max_length=4)),
                ('Titulo', models.CharField(max_length=100)),
                ('Salario', models.PositiveIntegerField()),
                ('Localizacao', models.CharField(max_length=100)),
                ('CargaHoraria', models.PositiveIntegerField()),
                ('Detalhes', models.TextField()),
                ('link', models.URLField()),
                ('QuantidadeVagas', models.PositiveIntegerField()),
                ('DataPostada', models.DateTimeField()),
            ],
        ),
    ]
