# Generated by Django 2.2.4 on 2022-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G1oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Escolaridade',
            field=models.CharField(choices=[('EF1I', 'Ensino fundamental 1 incompleto'), ('EF1C', 'Ensino fundamental 1 completo'), ('EF2I', 'Ensino fundamental 2 incompleto'), ('EF2I', 'Ensino fundamental 2 completo'), ('EMI', 'Ensino medio incompleto'), ('EMC', 'Ensino medio completo'), ('ESI', 'Ensino superior incompleto'), ('ESI', 'Ensino superior completo')], default='EF1I', max_length=4),
        ),
    ]
