# Generated by Django 2.2.4 on 2022-07-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G1oportunidades', '0002_auto_20220623_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TelegramId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
